#! /usr/bin/env python
# encoding: utf-8

bld.stlib(
    features='cxx',
    source=bld.path.ant_glob('**/*.cpp'),
    target='gauge',
    export_includes=['..'],
    use=['tables', 'boost_includes', 'cxxopts_includes'])
